# Register Api
POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "identity" : "user1@ggg.mail",
		"firstName" : "someone",
		"lastName" : "Codecamp",
    "password" : "123456",
		"confirmPassword" : "123456"
}
###
# Login Api
POST http://localhost:8899/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "identity" : "bobby@ggg.mail",
    "password" : "123456"
}

###

GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUwOTA5MDExLCJleHAiOjE3NTIyMDUwMTF9.XU-RQOjxrqfgYsDcjUI1rOtcg-l72Ve-NVxTOCo3vi0

### Create new post
POST http://localhost:8899/api/post HTTP/1.1
Content-Type: application/json

{
	"message" : "Hello, CC20"
}

### Get all posts
GET http://localhost:8899/api/post HTTP/1.1
Content-Type: application/json




